name: custom_weapon
main: me.gwanjong.gwanjung.Main
version: 0.1.0
api-version: '1.19'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.10
  - org.jetbrains.kotlin:kotlin-reflect:1.8.10
  - io.github.monun:kommand-core:3.1.0
  - io.github.monun:tap-core:4.8.0
  - io.github.monun:invfx-core:3.2.0